### ISSUE TITLE
bz init wipes exisitng configuration for pybugz

### ISSUE THREAD

**Issue by jbeich** [pgollucci/freebsd-bugzilla-cli#1]
I'm using pybugz for more than just FreeBSD Bugzilla. After running `bz init` my configuration in ~/.bugzrc is gone. At least it doesn't touch ~/.bugz_tokens.

**Comment by pgollucci** [comment]
That was intentional originally.  I can either add a flag or prompt.  I'll probably have to add a question about the connection name then too since it may or may not no longer be the default.

**Comment by pgollucci** [comment]
going to pass --connection for the pybugz backend

**Comment by pgollucci** [comment]
It will now  check and output what to add if it exists.  Fixed in 0.10.8
