### ISSUE TITLE
Non-canonical spelling of FreeBSD in the genarated ~/.bugzrc

### ISSUE THREAD

**Issue by jbeich** [pgollucci/freebsd-bugzilla-cli#3]
pybugz recently (in master, a year ago) added default connection profiles as pybugz.d/*.conf. Operating system names there aren't abbreviated. See williamh/pybugz#86 for FreeBSD profile is going to look like.

Can you replace `FBSD` with `FreeBSD`?

```
$ bz init
[...]

$ cat ~/.bugzrc                                                                   ~
[default]
connection=FBSD

[FBSD]
base=https://bugs.freebsd.org/bugzilla/xmlrpc.cgi
user=foo
password=foo
```

**Comment by pgollucci** [comment]
sure can.

**Comment by pgollucci** [comment]
now renamed in 0.10.8
